[uwsgi]
# Set the working directory to the project root (where manage.py is located)
chdir = /home/ubuntu/Lab-03-Group-06/backend/debatrix

# Point to the WSGI file within the Django project
wsgi-file = /home/ubuntu/Lab-03-Group-06/backend/debatrix/debatrix/wsgi.py

module = debatrix.wsgi:application

socket = 127.0.0.1:8000
master = true
disable-logging = true
processes = 2
threads = 4

