# Generated by Django 5.1.1 on 2024-10-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_debate_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='likes',
            new_name='percentage',
        ),
    ]
