# Generated by Django 5.1.1 on 2024-10-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_likes_debate_percentage'),
        ('auth_app', '0003_userprofile_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='userProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='auth_app.userprofile'),
        ),
    ]
