# Generated by Django 5.1.1 on 2024-10-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_debate_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='userProfile',
        ),
    ]
