# Generated by Django 5.1.1 on 2024-10-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment'),
        ('api', '0005_remove_debate_userprofile'),
    ]

    operations = [
    ]
