# Generated by Django 5.1.1 on 2024-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0004_comment_0005_remove_debate_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debateId', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
