# Generated by Django 5.1.1 on 2024-10-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0004_comment_0005_remove_debate_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
    ]
