# Generated by Django 5.1.1 on 2024-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='numOfPercentages',
            field=models.IntegerField(default=0),
        ),
    ]
