# Generated by Django 5.1.1 on 2024-10-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_debate_number_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='number_comments',
            field=models.IntegerField(default=20),
        ),
    ]
