# Generated by Django 5.1.1 on 2024-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_debate_number_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='number_comments',
        ),
        migrations.AddField(
            model_name='debate',
            name='numberComments',
            field=models.IntegerField(default=0),
        ),
    ]
