# Generated by Django 5.1.1 on 2024-10-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_debate_numofpercentages'),
        ('api', '0009_remove_debate_number_comments_debate_numbercomments'),
    ]

    operations = [
    ]
