# Generated by Django 5.1.1 on 2024-10-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_merge_20241019_2337"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="percentage",
            name="debateId",
        ),
        migrations.RemoveField(
            model_name="percentage",
            name="username",
        ),
        migrations.AddField(
            model_name="percentage",
            name="debate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="percentages",
                to="api.debate",
            ),
        ),
        migrations.AddField(
            model_name="percentage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
