# Generated by Django 5.1.1 on 2024-10-20 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_remove_percentage_debateid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="percentage",
            unique_together={("user", "debate")},
        ),
    ]
