# Generated by Django 5.1.1 on 2024-10-22 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_percentage_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="percentage",
            unique_together=set(),
        ),
    ]
