# Generated by Django 5.1.2 on 2024-10-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pinneddebates'),
        ('api', '0013_alter_percentage_unique_together'),
    ]

    operations = [
    ]
