# Generated by Django 5.1.1 on 2024-10-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_percentage_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="percentage",
            name="user",
            field=models.CharField(default="Anonymous", max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="percentage",
            unique_together={("user", "debate")},
        ),
    ]
