# Generated by Django 5.1.1 on 2024-10-23 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_merge_20241023_0939"),
        ("api", "0015_alter_percentage_user"),
    ]

    operations = []
