# Generated by Django 5.1.1 on 2024-10-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_merge_20241023_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="percentage",
            name="user",
            field=models.CharField(default="Anonymous", max_length=150),
        ),
    ]
