# Generated by Django 5.1.1 on 2024-10-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_percentage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('modelfile', models.CharField(max_length=10000)),
            ],
        ),
    ]
