# Generated by Django 5.1.1 on 2024-10-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_percentage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
