# Generated by Django 5.1.1 on 2024-10-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profilepicture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
