# Generated by Django 5.1.1 on 2024-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_chatbot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='modelfile',
            field=models.TextField(),
        ),
    ]
