# Generated by Django 5.1.1 on 2024-10-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_comment_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='debateId',
            field=models.IntegerField(unique=True),
        ),
    ]
