# Generated by Django 5.1.1 on 2024-10-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_debate_debateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='debateId',
            field=models.CharField(max_length=20),
        ),
    ]
