# Generated by Django 5.1.1 on 2024-10-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_debate_debateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_debate',
            field=models.IntegerField(),
        ),
    ]
