# Generated by Django 5.1.1 on 2024-10-24 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_debate_debateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debate'),
        ),
    ]
