# Generated by Django 5.1.1 on 2024-10-24 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_comment_parent_debate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_comments', to='api.debate'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='debateId',
            field=models.CharField(max_length=20),
        ),
    ]
