# Generated by Django 5.1.1 on 2024-10-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_chatbot_modelfile'),
        ('api', '0026_alter_comment_parent_debate_alter_debate_debateid'),
    ]

    operations = [
    ]
