# Generated by Django 5.1.1 on 2024-10-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20241024_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='debateId',
            field=models.IntegerField(),
        ),
    ]
