# Generated by Django 5.1.1 on 2024-10-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
